### ISSUE TITLE
Broken on latest rust nightly

### ISSUE THREAD

**Issue by tdaede** [pcwalton/pathfinder#106]
```
$ npm run build

> pathfinder-demo@0.1.0 build /home/thomas/sandbox/pathfinder/demo/client
> webpack

HandlebarsPlugin: + helper 'octicon'
HandlebarsPlugin: + partial 'partials/header.html'
HandlebarsPlugin: + partial 'partials/navbar.html'
HandlebarsPlugin: + partial 'partials/rotate.html'
HandlebarsPlugin: + partial 'partials/spinner.html'
HandlebarsPlugin: + partial 'partials/switch.html'
HandlebarsPlugin: created output './3d-demo.html'
HandlebarsPlugin: created output './benchmark.html'
HandlebarsPlugin: created output './doc-before-content.html'
HandlebarsPlugin: created output './doc-header.html'
HandlebarsPlugin: created output './index.html'
HandlebarsPlugin: created output './mesh-debugger.html'
HandlebarsPlugin: created output './reference-test.html'
HandlebarsPlugin: created output './svg-demo.html'
HandlebarsPlugin: created output './text-demo.html'

ts-loader: Using typescript@2.9.2 and /home/thomas/sandbox/pathfinder/demo/client/tsconfig.json
Building documentation for `/home/thomas/sandbox/pathfinder`...
warning: patch for the non root package will be ignored, specify patch at the workspace root:
package:   /home/thomas/sandbox/pathfinder/demo/server/Cargo.toml
workspace: /home/thomas/sandbox/pathfinder/Cargo.toml

warning: Patch `ring v0.12.2 (https://github.com/SergioBenitez/ring?branch=v0.12#9ccfa153)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.

warning: Patch `ring v0.12.2 (https://github.com/SergioBenitez/ring?branch=v0.12#9ccfa153)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.

   Compiling version_check v0.1.4

   Compiling proc-macro2 v0.4.19
   Compiling cfg-if v0.1.5
   Compiling nodrop v0.1
.12
   Compiling scopeguard v0.3.3

   Compiling unicode-xid v0.1.0

   Compiling memoffset v0.2.1

   Compiling libc v0.2.43

   Compiling rayon-core v1.4.1

   Compiling cc v1.0.25

   Compiling num-traits v0.2.6


   Compiling serde v1.0.79


   Compiling pkg-config v0.3.14

 
   Checking matches v0.1.8
   Compiling gcc v0.3.54

   Compiling unicode-normalization v0.1.7

   Compiling httparse v1.3.2

   Compiling num-integer v0.1.39


   Compiling yansi
 v0.4.0

  
  Checking byteorder v1.2.6

    Checking
 lazy_static v0.2.11

   Compiling untrusted v0.5.1

   Compiling 
ryu v0.2.6

   Compiling void
 v1.0.2

   Compiling rayon v
1.0.2

   Compiling num-iter
 v0.1.37

    Checking ucd-util v0.1.1

   Compiling safemem v0
.2.0

   Compiling percent-encoding v1.0.1

   Compiling failure_derive
 v0.1.2

   Compiling regex
 v1.0.5

    Checking either
 v1.5.0

    Checking rustc-demangle v0.
1.9

   Compiling safemem v0.3.0

    Checking quick-error v1.2.2

    Checking 
traitobject v0.1.0

    Checking
 adler32 v1.0.3

    Checking typeable v0.1.2

   Compiling language-tags v0.2.2

    Checking 
utf8-ranges v1.0.1

    Checking state v0.4
.1

    Checking
 itoa v0.4.3

    Checking termcolor v1.0.4

    Checking color_quant
 v1.0.1

    Checking
 pear v0.0.20

    Checking bitflags v1.0.4

 
   Checking 
lzw v0.10.0


    Checking unicode-width v0.1.5

   Compiling ordermap v0.2.13

    Checking same-file v1.0.3

    Checking linked-hash-map v0.4.2


    Checking vec_map v0.8.1

    Checking scoped_threadpool v0.1.9

    Checking strsim v0.7.0

 
 
  Checking ansi_term v0.11.0

    Checking bit-vec v0.4.4

    Checking float-ord v0.2.0

    Checking half v1.2.0
    Checking crossbeam-utils v0.2.2

    Checking log v0.4.5

 
   Checking unicode-bidi v0.3.4

    Checking arrayvec v0.4.7

   Compiling unreachable v1.0.0

    Checking inflate v0.4.3

    Checking humantime v1.1.1

    Checking itertools v0.7.8

    Checking textwrap v0.10.0

    Checking walkdir v2.
2.5

    Checking regex-syntax v0.6.2

   Compiling lazy_static v1.1.0

   Compiling memchr v2.1.0

   Compiling unicase v1.4.2

   Compiling smallvec v0.6.5

    Checking gif v0.10.0

    Checking lru-cache v0.1.1

    Checking log v0.3.9

   Compiling pear_codegen v0.0.20

   Compiling rocket v0.3.16

   Compiling rocket_codegen v0.3.16

    Checking base64 v0.6.0

    Checking base64 v0.9.3
    Checking deflate v0.7.18

   Compiling servo-fontconfig-sys v4.0.6

    Checking mime v0.2.6

    Checking thread_local v0.3.6

   Compiling num_cpus v1.8.0

   Compiling time v0.1.40
   Compiling isatty v0.1.9

    Checking crossbeam-epoch v0.3.1

    Checking atty v0.2.11

    Checking dirs v1.0.3
    Checking memmap v0.6.2

    Checking clap v2.32.0

    Checking crossbeam-deque v0.2.0

   Compiling quote v0.6.8

    Checking aho-corasick v0.6.8

error[E0599]: no variant named `concat` found for type `syntax::tokenstream::TokenStream` in the current scope
   --> /home/thomas/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.0.20/src/lib.rs:330:67

    |
330 |                 mac.node.tts = ThinTokenStream::from(TokenStream::concat(streams));
    |                                                      -------------^^^^^^
    |                                                      |
    |                                                      variant not found in `syntax::tokenstream::TokenStream`


   Compiling cmake v0.1.34

   Compiling backtrace-sys v0.1.24

   Compiling miniz-sys v0.1.
10

error: aborting due to previous error



For more information about this error, try `rustc --explain E0599`.

error: Could not compile `pear_codegen`.
warning: build failed, waiting for other jobs to finish...

error: build failed

Failed to build documentation for `/home/thomas/sandbox/pathfinder`!
/home/thomas/sandbox/pathfinder/demo/client/build/rustdoc-webpack-plugin/index.js:33
                        throw new Error(message);
                        ^

Error: Failed to build documentation for `/home/thomas/sandbox/pathfinder`!
    at ChildProcess.cargo.on.code (/home/thomas/sandbox/pathfinder/demo/client/build/rustdoc-webpack-plugin/index.js:33:31)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pathfinder-demo@0.1.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathfinder-demo@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thomas/.npm/_logs/2019-01-15T21_51_44_682Z-debug.log
```

**Comment by Asone** [comment]
Hi, 
this is a known bug for which a PR has been opened [here](https://github.com/pcwalton/pathfinder/pull/105). You'll need to update to rocket 0.4 in order to fix the bug. 

You'll have to wait for the PR to be merge or make the related update yourself in the meantime.

**Comment by pcwalton** [comment]
Rocket is no longer used with Pathfinder 3.
