### ISSUE TITLE
LoremIpsum example apparently now requires OpenGL 4.4+ ?

### ISSUE THREAD

**Issue by lqd** [pcwalton/pathfinder#13]
It seems this line ended up bumping the OpenGL version requirement to 4.4+ for this example: https://github.com/pcwalton/pathfinder/commit/49408b95cb9a159a0912e38cd81a953d3e2a0ae1#diff-65d637d8d8f74f7ebed766c5a7d9caddR957

It calls the compute_shader crate's "OpenGL 4.5+ backend" (`api::gl:queue::submit_clear` calls `gl::ClearTexImage` which is a 4.4 API).

Did you mean to make Pathfinder 4.3+ but the examples 4.4+ ? 

The lorem ipsum example crashes on 4.3:
```
Running target\debug\examples\lorem-ipsum.exe resources/tests/nimbus-sans/NimbusSanL-Regu.ttf
thread 'main' panicked at 'gl function was not loaded', g:\work\tests\pathfinder\target\debug\build\gl-256f76015a3dc339\out/bindings.rs:20591
stack backtrace:
   0:        0x1402f6898 - std::panicking::default_hook::{{closure}}
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:356
   1:        0x1402f5da4 - std::panicking::default_hook
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:367
   2:        0x1402f96ed - std::panicking::rust_panic_with_hook
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:555
   3:        0x1402e4327 - std::panicking::begin_panic<&str>
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:517
   4:        0x1402e4bc5 - gl::missing_fn_panic
                        at C:\Users\lqd\.cargo\registry\src\github.com-1ecc6299db9ec823\gl-0.6.1\src\lib.rs:79
   5:        0x1402df4c2 - gl::ClearTexImage
                        at g:\work\tests\pathfinder\target\debug\build\gl-256f76015a3dc339\out\bindings.rs:3104
   6:        0x1402e37e3 - compute_shader::api::gl::queue::submit_clear
                        at C:\Users\lqd\.cargo\git\checkouts\compute-shader-f4827bcbd5ce554b\c155f7f\src\api\gl\queue.rs:137
   7:        0x13ff6aeba - compute_shader::queue::Queue::submit_clear
                        at C:\Users\lqd\.cargo\git\checkouts\compute-shader-f4827bcbd5ce554b\c155f7f\src\queue.rs:139
   8:        0x13ffe9745 - lorem_ipsum::create_image
                        at g:\work\tests\pathfinder\examples\lorem-ipsum.rs:957
   9:        0x13ffe4f4b - lorem_ipsum::Renderer::new
                        at g:\work\tests\pathfinder\examples\lorem-ipsum.rs:399
  10:        0x13ffe2faa - lorem_ipsum::main
                        at g:\work\tests\pathfinder\examples\lorem-ipsum.rs:150
  11:        0x1402fa3e1 - panic_unwind::__rust_maybe_catch_panic
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libpanic_unwind\lib.rs:98
  12:        0x1402f99aa - std::rt::lang_start
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\rt.rs:51
  13:        0x13fff1bab - main
  14:        0x140311567 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:255
  15:         0x76ca59cc - BaseThreadInitThunk
error: process didn't exit successfully: `target\debug\examples\lorem-ipsum.exe resources/tests/nimbus-sans/NimbusSanL-Regu.ttf` (exit code: 101)
```

**Comment by pcwalton** [comment]
Ah, I forgot that `glClearTexImage` is too new. I guess I'll use an FBO instead. Thanks for the report!

**Comment by pcwalton** [comment]
I've tagged this issue as "classic", as it likely only applies to Pathfinder 1 ("classic Pathfinder"). Once Pathfinder 2 matures, this issue will be closed. Feel free to reopen if it is still an issue with the new version. Thanks!

**Comment by pcwalton** [comment]
This issue affected Pathfinder 1, which is now obsolete. Please feel free to reopen if this is still an issue with Pathfinder 2.
