### ISSUE TITLE
Examples fails on Windows 10

### ISSUE THREAD

**Issue by UK992** [pcwalton/pathfinder#15]
> Windows 10 64-bit build 14393
> 
> GPU 1: NVIDIA GeForce GT 650M
> GPU 2: Intel(R) HD Graphics 4000
> 
> OpenGL Version: 4.5.0 NVIDIA 373.06
> GLSL (OpenGL Shading Language) Version: 4.50 NVIDIA

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ComputeError(CompileFailed("ERROR: 0:12: \'#extension\' :  \'GL_ARB_compute_shader\' is not supported\nERROR: 0:13: \'#extension\' :  \'GL_ARB_explicit_uniform_location\' is not supported\nERROR: 0:14: \'#extension\' :  \'GL_ARB_shader_image_load_store\' is not supported\nERROR: 0:15: \'#extension\' :  \'GL_ARB_shader_storage_buffer_object\' is not supported\nERROR: 0:51: \'local_size_x\' : syntax error syntax error\n\n\u{0}\u{0}"))', src\libcore\result.rs:860
stack backtrace:
   0:     0x7ff611d3e197 - std::panicking::default_hook::{{closure}}
                        at C:\projects\rust\src\libstd\panicking.rs:356
   1:     0x7ff611d3d6c4 - std::panicking::default_hook
                        at C:\projects\rust\src\libstd\panicking.rs:367
   2:     0x7ff611d40fe1 - std::panicking::rust_panic_with_hook
                        at C:\projects\rust\src\libstd\panicking.rs:545
   3:     0x7ff611d40e98 - std::panicking::begin_panic<collections::string::String>
                        at C:\projects\rust\src\libstd\panicking.rs:507
   4:     0x7ff611d40db4 - std::panicking::begin_panic_fmt
                        at C:\projects\rust\src\libstd\panicking.rs:491
   5:     0x7ff611d40d49 - std::panicking::rust_begin_panic
                        at C:\projects\rust\src\libstd\panicking.rs:467
   6:     0x7ff611d48047 - core::panicking::panic_fmt
                        at C:\projects\rust\src\libcore\panicking.rs:69
   7:     0x7ff611ca8555 - core::result::unwrap_failed<pathfinder::error::InitError>
                        at C:\projects\rust\src\libcore\macros.rs:29
   8:     0x7ff611c9f057 - core::result::Result<pathfinder::rasterizer::Rasterizer, pathfinder::error::InitError>::unwrap<pathfinder::rasterizer::Rasterizer,pathfinder::error::InitError>
                        at C:\projects\rust\src\libcore\result.rs:737
   9:     0x7ff611cb41fe - benchmark::main
                        at C:\github\pathfinder\examples\benchmark.rs:62
  10:     0x7ff611d41b11 - panic_unwind::__rust_maybe_catch_panic
                        at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  11:     0x7ff611d412ba - std::rt::lang_start
                        at C:\projects\rust\src\libstd\rt.rs:51
  12:     0x7ff611cbdbcb - main
  13:     0x7ff611d691d0 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  14:     0x7ffdd4d38363 - BaseThreadInitThunk
error: process didn't exit successfully: `target\debug\examples\benchmark.exe` (exit code: 101)
```

**Comment by pcwalton** [comment]
I've tagged this issue as "classic", as it likely only applies to Pathfinder 1 ("classic Pathfinder"). Once Pathfinder 2 matures, this issue will be closed. Feel free to reopen if it is still an issue with the new version. Thanks!

**Comment by pcwalton** [comment]
This issue affected Pathfinder 1, which is now obsolete. Please feel free to reopen if this is still an issue with Pathfinder 2.
