### ISSUE TITLE
Documenting fails on Win 10

### ISSUE THREAD

**Issue by MSleepyPanda** [pcwalton/pathfinder#77]
Steps to reproduce:
Invoke `npm run build` in `demo/client`

Output
```
rustdoc: too many file operands
Try 'rustdoc --help' for more information.

error: Could not document `generate-gamma-lut`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name generate_gamma_lut utils\gamma-lut\src\main.rs -o C:\Users\Matthias Prechtl\Documents\Projekte\pathfinder\target\doc -L dependency=C:\Users\Matthias Prechtl\Documents\Projekte\pathfinder\target\debug\deps --extern image=C:\Users\Matthias Prechtl\Documents\Projekte\pathfinder\target\debug\deps\libimage-6cf24f00b3f27486.rlib --extern clap=C:\Users\Matthias Prechtl\Documents\Projekte\pathfinder\target\debug\deps\libclap-1b29bebce5980047.rlib --extern log=C:\Users\Matthias Prechtl\Documents\Projekte\pathfinder\target\debug\deps\liblog-1cfd1292a00e233a.rlib --html-in-header=C:\Users\Matthias Prechtl\Documents\Projekte\pathfinder\demo\client\doc-header.html --html-before-content=C:\Users\Matthias Prechtl\Documents\Projekte\pathfinder\demo\client\doc-before-content.html` (exit code: 1)

warning: build failed, waiting for other jobs to finish...

error: build failed

Failed to build documentation for `C:\Users\Matthias Prechtl\Documents\Projekte\pathfinder`!
C:\Users\Matthias Prechtl\Documents\Projekte\pathfinder\demo\client\build\rustdoc-webpack-plugin\index.js:33
                        throw new Error(message);
                        ^

Error: Failed to build documentation for `C:\Users\Matthias Prechtl\Documents\Projekte\pathfinder`!
    at ChildProcess.cargo.on.code (C:\Users\Matthias Prechtl\Documents\Projekte\pathfinder\demo\client\build\rustdoc-webpack-plugin\index.js:33:31)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```

This looks like a cargo/rust doc bug, since all you do is invoke `cargo doc`, but posting here first in case this is known

**Comment by pzmarzly** [comment]
Also happens on Linux. It's caused by space in working directory.

**Comment by pzmarzly** [comment]
[Related cargo issue](https://github.com/rust-lang/cargo/issues/3686)

For now, you can either move whole folder somewhere else, or edit `demo/client/build/rustdoc-webpack-plugin/index.js`, commenting out line with `env: Object.assign({RUSTDOCFLAGS: rustdocFlags}, process.env),` - you will lose custom header/footer in documentation.

**Comment by pcwalton** [comment]
Webpack is no longer used in Pathfinder 3.
