### ISSUE TITLE
demo build fails with rocket_codegen compile errors

### ISSUE THREAD

**Issue by jagan-veeraraghavan** [pcwalton/pathfinder#97]
I followed the steps listed on the Readme.md:
```
$ cd demo/client
$ npm install
$ npm run build
```
My rust and node versions
```
$node --version
v10.9.0
$ npm --version
6.4.1
$ rustup show
Default host: x86_64-apple-darwin

nightly-x86_64-apple-darwin (default)
rustc 1.30.0-nightly (0f063aef6 2018-09-03)
```
I have pasted a truncated log for the sake of brevity. 
```
ts-loader: Using typescript@2.9.2 and /tmp/pathfinder/demo/client/tsconfig.json
Building documentation for `/tmp/pathfinder`...
   Compiling rocket_codegen v0.4.0-dev (https://github.com/SergioBenitez/rocket#fd6d5771)

 Documenting pathfinder v0.2.0 (file:///tmp/pathfinder/utils/frontend)

error[E0432]: unresolved import `syntax::codemap`
 --> /Users/user/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/fd6d577/core/codegen/src/utils/parser_ext.rs:1:5
  |
1 | use syntax::codemap;
  |     ^^^^^^^^^^^^^^^ no `codemap` in the root
.....
367 | method_decorator!(options_decorator, Options);
    | ---------------------------------------------- in this macro invocation
    |

    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `shorten_to`, perhaps you need to implement it:
            candidate #1: `utils::span_ext::SpanExt`


error: aborting due to 30 previous errors


Some errors occurred: E0277, E0282, E0432, E0599, E0609.
For more information about an error, try `rustc --explain E0277`.

error: Could not compile `rocket_codegen`.
warning:
build failed, waiting for other jobs to finish...

error: build failed

Failed to build documentation for `/tmp/pathfinder`!
/tmp/pathfinder/demo/client/build/rustdoc-webpack-plugin/index.js:33
                        throw new Error(message);
                        ^

Error: Failed to build documentation for `/tmp/pathfinder`!
    at ChildProcess.cargo.on.code (/tmp/pathfinder/demo/client/build/rustdoc-webpack-plugin/index.js:33:31)
    at emitTwo (events.js:125:13)
```

Request help in resolving this issue.

**Comment by Bobo1239** [comment]
Can you try running `cargo update` in the pathfinder directory before doing the above? Rocket (a web framework) depends on nightly features so breaks somewhat regularly. Fortunately it's author pushes updates quite quickly.

**Comment by jagan-veeraraghavan** [comment]
@Bobo1239 `cargo update` fixed the issue.
